import { Edge, Node, Position } from "reactflow"

import texts from "./texts.json"

const NODE_GAP = 200

export const desktopNodes: Node[] = [
  {
    id: "node-community",
    position: { x: 120, y: 100 },
    data: { label: "Сообщество" },
    style: {
      fontSize: "32px",
      fontWeight: "regular",
      width: "auto",
      backgroundColor: "#E7EBF4",
    },
    targetPosition: Position.Right,
    sourcePosition: Position.Right,
  },
  {
    id: "node-trust",
    position: { x: NODE_GAP * 2 + 5, y: 100 },
    data: { label: "Доверие" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-text1",
    type: "customText",
    position: { x: NODE_GAP * 2 + 300, y: 80 },
    data: { label: texts.firstText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-shadow1",
    position: { x: NODE_GAP * 2 + 300, y: 125 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-recruitment",
    position: { x: 40, y: 320 },
    data: { label: "Набор и развитие" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    sourcePosition: Position.Right,
    targetPosition: Position.Left,
  },
  {
    id: "node-activity",
    position: { x: NODE_GAP * 2, y: 320 },
    data: { label: "Активность" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    targetPosition: Position.Left,
    sourcePosition: Position.Right,
  },
  {
    id: "node-text2",
    type: "customText",
    position: { x: NODE_GAP * 2 + 300, y: 320 },
    data: { label: texts.secondText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-shadow2",
    position: { x: NODE_GAP * 2 + 300, y: 345 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-consistency",
    position: { x: NODE_GAP * 2, y: 500 },
    data: { label: "Согласованность" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-text3",
    type: "customText",
    position: { x: NODE_GAP * 2 + 300, y: 490 },
    data: { label: texts.thirdText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-shadow3",
    position: { x: NODE_GAP * 2 + 300, y: 525 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-text4",
    type: "customText2",
    position: { x: 40, y: 440 },
    data: { label: texts.fourthText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-shadow4",
    position: { x: 40, y: 480 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-difficult",
    position: { x: NODE_GAP - 30, y: 650 },
    data: { label: "Преодоление трудностей" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    targetPosition: Position.Top,
    sourcePosition: Position.Top,
  },
  {
    id: "node-text5",
    type: "customText",
    position: { x: NODE_GAP - 30, y: 780 },
    data: { label: texts.fifthText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
  },
  {
    id: "node-shadow5",
    position: { x: NODE_GAP - 56, y: 780 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Top,
    sourcePosition: Position.Top,
  },
]

export const desktopEdges: Edge[] = [
  {
    id: "edge-community-trust",
    source: "node-community",
    target: "node-trust",
  },
  {
    id: "edge-trust-text1",
    source: "node-trust",
    target: "node-text1",
  },
  {
    id: "edge-trust-shadow1",
    source: "node-trust",
    target: "node-shadow1",
  },
  {
    id: "edge-recruitment-activity",
    source: "node-recruitment",
    target: "node-activity",
  },
  {
    id: "edge-activity-text2",
    source: "node-activity",
    target: "node-text2",
  },
  {
    id: "edge-activity-shadow2",
    source: "node-activity",
    target: "node-shadow2",
  },
  {
    id: "edge-concsistency-difficult",
    source: "node-consistency",
    target: "node-difficult",
    type: "step",
  },
  {
    id: "edge-consistency-shadow3",
    source: "node-consistency",
    target: "node-shadow3",
  },
  {
    id: "edge-recruitment-shadow4",
    source: "node-shadow4",
    target: "node-recruitment",
  },
  {
    id: "edge-trust-difficult",
    source: "node-trust",
    target: "node-difficult",
    type: "step",
  },
  {
    id: "edge-shadow5-difficult",
    source: "node-difficult",
    target: "node-shadow5",
  },
]

//Mobile flow for mobile view
export const mobileNodes: Node[] = [
  {
    id: "node-community",
    position: { x: 350, y: -370 },
    data: { label: "Сообщество" },
    style: {
      fontSize: "32px",
      fontWeight: "regular",
      width: "auto",
      backgroundColor: "#E7EBF4",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-trust",
    position: { x: 200, y: -270 },
    data: { label: "Доверие" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    targetPosition: Position.Left,
    sourcePosition: Position.Bottom,
  },
  {
    id: "node-text1",
    type: "customText",
    position: { x: 200, y: -180 },
    data: { label: texts.firstText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-shadow1",
    position: { x: 50, y: -170 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Top,
    sourcePosition: Position.Top,
  },
  {
    id: "node-recruitment",
    position: { x: 200, y: 50 },
    data: { label: "Набор и развитие" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    sourcePosition: Position.Left,
    targetPosition: Position.Bottom,
  },
  {
    id: "node-activity",
    position: { x: NODE_GAP * 2 - 200, y: 480 },
    data: { label: "Активность" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    targetPosition: Position.Left,
    sourcePosition: Position.Bottom,
  },
  {
    id: "node-text2",
    type: "customText",
    position: { x: NODE_GAP * 2 - 200, y: 590 },
    data: { label: texts.secondText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-shadow2",
    position: { x: NODE_GAP * 2 - 330, y: 580 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Top,
    sourcePosition: Position.Top,
  },
  {
    id: "node-consistency",
    position: { x: NODE_GAP * 2 - 200, y: 300 },
    data: { label: "Согласованность" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    targetPosition: Position.Bottom,
    sourcePosition: Position.Left,
  },
  {
    id: "node-text3",
    type: "customText",
    position: { x: NODE_GAP * 2 - 200, y: 400 },
    data: { label: texts.thirdText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-shadow3",
    position: { x: NODE_GAP * 2 - 290, y: 400 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Top,
    sourcePosition: Position.Top,
  },
  {
    id: "node-text4",
    type: "customText2",
    position: { x: 210, y: 160 },
    data: { label: texts.fourthText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Left,
    sourcePosition: Position.Left,
  },
  {
    id: "node-shadow4",
    position: { x: 118, y: 160 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Top,
    sourcePosition: Position.Top,
  },
  {
    id: "node-difficult",
    position: { x: NODE_GAP + 10, y: 700 },
    data: { label: "Преодоление трудностей" },
    style: { fontSize: "32px", fontWeight: "regular", width: "auto" },
    targetPosition: Position.Left,
    sourcePosition: Position.Bottom,
  },
  {
    id: "node-text5",
    type: "customText",
    position: { x: NODE_GAP - 30, y: 850 },
    data: { label: texts.fifthText },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
  },
  {
    id: "node-shadow5",
    position: { x: NODE_GAP - 65, y: 860 },
    data: { label: "" },
    style: {
      border: "none",
      background: "none",
      boxShadow: "none",
      width: "auto",
      minWidth: "450px",
      maxWidth: "600px",
    },
    targetPosition: Position.Top,
    sourcePosition: Position.Top,
  },
]

export const mobileEdges: Edge[] = [
  {
    id: "edge-community-trust",
    source: "node-community",
    target: "node-trust",
  },
  {
    id: "edge-trust-text1",
    source: "node-trust",
    target: "node-text1",
  },
  {
    id: "edge-trust-shadow1",
    source: "node-trust",
    target: "node-shadow1",
  },
  {
    id: "edge-recruitment-activity",
    source: "node-recruitment",
    target: "node-activity",
  },
  {
    id: "edge-activity-text2",
    source: "node-activity",
    target: "node-text2",
  },
  {
    id: "edge-activity-shadow2",
    source: "node-activity",
    target: "node-shadow2",
  },
  {
    id: "edge-concsistency-difficult",
    source: "node-consistency",
    target: "node-difficult",
    type: "step",
  },
  {
    id: "edge-consistency-shadow3",
    source: "node-shadow3",
    target: "node-consistency",
  },
  {
    id: "edge-recruitment-shadow4",
    source: "node-shadow4",
    target: "node-recruitment",
  },
  {
    id: "edge-trust-recruitment",
    source: "node-recruitment",
    target: "node-trust",
    type: "step",
  },
  {
    id: "edge-shadow5-difficult",
    source: "node-difficult",
    target: "node-shadow5",
  },
]
