/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StrategyImport } from './routes/strategy'
import { Route as FaqImport } from './routes/faq'
import { Route as CommunityImport } from './routes/community'
import { Route as ApplyImport } from './routes/apply'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StrategyRoute = StrategyImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRoute,
} as any)

const FaqRoute = FaqImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any)

const CommunityRoute = CommunityImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRoute,
} as any)

const ApplyRoute = ApplyImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyImport
      parentRoute: typeof rootRoute
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqImport
      parentRoute: typeof rootRoute
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/strategy': typeof StrategyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/strategy': typeof StrategyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/community': typeof CommunityRoute
  '/faq': typeof FaqRoute
  '/strategy': typeof StrategyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apply' | '/community' | '/faq' | '/strategy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apply' | '/community' | '/faq' | '/strategy'
  id: '__root__' | '/' | '/apply' | '/community' | '/faq' | '/strategy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  CommunityRoute: typeof CommunityRoute
  FaqRoute: typeof FaqRoute
  StrategyRoute: typeof StrategyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  CommunityRoute: CommunityRoute,
  FaqRoute: FaqRoute,
  StrategyRoute: StrategyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/apply",
        "/community",
        "/faq",
        "/strategy"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/apply": {
      "filePath": "apply.tsx"
    },
    "/community": {
      "filePath": "community.tsx"
    },
    "/faq": {
      "filePath": "faq.tsx"
    },
    "/strategy": {
      "filePath": "strategy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
